### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by captn3m0** [BlrChessClub/BCC-website#103]
Laundry list of ideas, suggestions etc. See #99 for context. Keeping this for myself, so I have a list to follow. If you'd like to help, please reach out!

The priority is for maintainability -> usability -> performance, but I can get distracted. Ideal state is to make it easy for maintainers to create new events, and not worry about doing anything once they are done - they should automatically be archived.

## Performance

- [ ] #114
- [x] Drop Google fonts (slow). Bootstrap default uses systemstack, and looks decent. We are currently including both Lato and Roboto.
- [x] Reduce image dimensions for testimonial avatars.
- [x] In general, optimize images where we can.
- [ ] #115

## Maintainability

- [x] Find more common HTML and move it to layouts.
- [x] Merge the various `_includes/head*`  files together
- [x] Switch to `YYYYMMDD` for event dates in URLs. Sorting is confusing right now.
- [x] Convert event to a real layout, so we can set event title, image, time, venue, payment-link attributes and not have to worry about writing HTML. Simple markdown.
- [x] Convert testimonials to a collection, so we can add more easily
- [x] Load team and gallery pics dynamically
- [x] Upgrade Bootstrap to v4.6.2, latest version of the v4 release (https://endoflife.date/bootstrap)
- [ ] #107
- [ ] #108
- [ ] #109
- [x] Switch to a GitHub Actions powered Jekyll Build
- [ ] #110
- [x] Switch Gallery to automatic, so it picks up images from disk directly
- [x] Cleanup index.html
- [x] Automatically show upcoming events on the homepage (or none if there aren't any)

## SEO and Usability
- [ ] #111
- [x] Add schema.org/Event LD-JSON for events.
- [x] Open Graph tags.
- [x] Create a /events page.
- [ ] #112
- [ ] #113
- [x] Better event URLs.

**Comment by captn3m0** [comment]
Improved the gallery page so it automatically picks up images in the gallery directory.

**Comment by captn3m0** [comment]
As a summary of the work so far, we've gone from (ignoring any dependencies):

Language|files|blank|comment|code
:-------|-------:|-------:|-------:|-------:
HTML|30|3372|2031|14559
CSS|2|139|22|1163
SCSS|1|155|25|623
JavaScript|1|9|6|47
--------|--------|--------|--------|--------
SUM:|34|3675|2084|16392

to

Language|files|blank|comment|code
:-------|-------:|-------:|-------:|-------:
HTML|45|376|34|2833
SCSS|5|3|30|1435
CSS|3|54|7|331
JavaScript|2|40|68|196
Markdown|12|5|0|118
YAML|1|1|2|29
--------|--------|--------|--------|--------
SUM:|68|479|141|4942

**Comment by captn3m0** [comment]
Added a tiny easter egg in the footer:

![image](https://github.com/user-attachments/assets/40b8dbba-d360-4b36-94fa-74eebd11d6b4)

**Comment by captn3m0** [comment]
Converted half of the events to a new markdown based layout. We no longer need to write HTML to manage events! This is how the upcoming Chess Connect on 28th July looks now:

```markdown
---
location: the-market-place
title: "Chess Connect Rapid"
image: chessconnect_28072024.jpeg
variations:
- standard-swiss
layout: newevent
payment:
  price: 250
  razorpay: pl_OT5SsIPvJBThGj
startsAt: 2024-07-28T10:00
endsAt: 2024-07-28T15:30
---
## Event Details

Join us for our next chess meetup for a day filled with chess magic! Whether
you're a seasoned player or just discovering your love for the game, come
embrace the thrill of chess, forge new connections, and make every move
count. Let's bring the chessboard to and continue our journey of checkmates
and camaraderie!

## What's Included

* 5 Hours of **Rapid Chess** (Format 10+5)
* `Special Prizes` for the Top 3 Players
* Chance to Win a `Chess.com Diamond Membership` through Lucky Draw

## Schedule

- Registration and Player Briefing (10:00 AM)
- Round 1 (10:15 AM)
- Round 2 (10:50 AM)
- Round 3 (11:25 AM)
- Round 4 (12:00 PM)
- `Lunch Break (12:35 PM)`
- Round 5 (1:20 PM)
- Round 6 (1:55 PM)
- Round 7 (2:30 PM)

```

Notably:

1. Variations are automatically picked up (see `_data/variations.yml` for a complete list)
2. Having start and endDate on the event allows us to show only upcoming events on the homepage. We also hide payment buttons for past events
3. A payment link ID means the Razorpay form is automatically generated.
4. Existing formatting is supported.
5. The site also supports multiple locations, and multiple variations. We can also write custom HTML if we need to.

Have another 13 chess connect events to convert, will get to them later.

**Comment by captn3m0** [comment]
Crossed off a few more items:

- Converted all events to the new format (`layout: event` instead of `layout: newevent`)
- Added a new events page: https://bangalorechessclub.in/events/
- We have an API as well now: https://bangalorechessclub.in/api/events.json, https://bangalorechessclub.in/api/upcoming.json

Final Numbers after all events are now in markdown:

Language|files|blank|comment|code
:-------|-------:|-------:|-------:|-------:
SCSS|5|49|28|1640
HTML|20|70|25|842
Markdown|39|112|0|736
CSS|2|21|36|224
JavaScript|3|39|73|199
YAML|1|1|5|46
JSON|1|1|0|31
--------|--------|--------|--------|--------
SUM:|71|293|167|3718

Most stuff on this TODO list is done, will close this issue and create separate ones.
